### ISSUE TITLE
Cant close skills menu

### ISSUE THREAD

**Issue by RoyceROlls1** [Burn-One-Studios/B1-skillz#11]
I have no errors but I cant close the menu. It wont even let me to t/ commands after I open it

**Comment by Kingsage311** [comment]
You didn't install it correctly please remove the -qb or -esx from the name the branch name should never be in the resource
[B1-skillz Installation Guide](https://docs.burnonestudios.com/FiveM-Resources/B1-skillz/Installation%20Guide/)

ESC is the key to close the menu
