### ISSUE TITLE
['icon'] = 'fas fa-walking', not showing

### ISSUE THREAD

**Issue by xrtw** [Burn-One-Studios/B1-skillz#5]
hello, icons are not showing

**Comment by Kingsage311** [comment]
I need more info any errors or a screenshot there isn't enough info to go off of here

**Comment by Kingsage311** [comment]
Closing this as no reply for almost a month if you are talking about the NUI it does not support the font awsome icons (yet) it was on there because there is a choice for the QB version to use qb-menu we plan on adding font awsome support soon.

**Comment by Kingsage311** [comment]
![skillmenuprev](https://user-images.githubusercontent.com/84582203/202392916-79a55987-f9c4-4394-906f-536eafad1282.png)
New update just added it to the nui, please update and you will see the font awsome icons now
